global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '******@gmail.com'
  smtp_auth_username: '********@gmail.com'
  smtp_auth_password: '*******'

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: '***********@gmail.com'
